name: 部署服务
on:
  push:
    branches:
      - master
        #paths-ignore:
        #- README.md
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps: # 自动化步骤
      - uses: actions/checkout@v2 # 第一步，下载代码仓库

      - name: Use Node.js 
        uses: actions/setup-node@v1

      - name: Install Dependencies  # 第二步，安装依赖
        run: npm install

      - name: Build              # 第三步，打包代码
        run: npm run build

      - name: Deploy to Server # 第二步，rsync推文件
        uses: AEnterprise/rsync-deploy@v1.0 # 使用别人包装好的步骤镜像
        env:
          DEPLOY_KEY: ${{ secrets.SSH_SECRET }} # 引用配置，SSH私钥
          ARGS: -avz --delete --exclude='*.pyc' # rsync参数，排除.pyc文件
          SERVER_PORT: "22" # SSH端口
          FOLDER: ./dist/ # 要推送的文件夹，路径相对于代码仓库的根目录
          SERVER_IP: ${{ secrets.SSH_HOST }} # 引用配置，服务器的host名（IP或者域名domain.com）
          USERNAME: ${{ secrets.SSH_USER }} # 引用配置，服务器登录名
          SERVER_DESTINATION: ${{ secrets.DEPLOY_PATH }} # 部署到目标文件夹

